import type { Metadata } from "next";
import "./main.css";
import Navigation from "@/components/navigation";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
